// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'loginpage_viewmodel.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3xGkvLeFJgFTHH8BgWc9ATUnyLOPC8ls',
    appId: '1:1019215614982:web:d1503e342bf4be00f15f87',
    messagingSenderId: '1019215614982',
    projectId: 'rentify-t05c21',
    authDomain: 'rentify-t05c21.firebaseapp.com',
    storageBucket: 'rentify-t05c21.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD70Od6JTX39ttk0YbtecStt-pMXYZzsDE',
    appId: '1:1019215614982:android:119a7982b8e08452f15f87',
    messagingSenderId: '1019215614982',
    projectId: 'rentify-t05c21',
    storageBucket: 'rentify-t05c21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUAyu6r1I7IGATrlGe5zT14fWWxNGS9us',
    appId: '1:1019215614982:ios:fe1f398115be0123f15f87',
    messagingSenderId: '1019215614982',
    projectId: 'rentify-t05c21',
    storageBucket: 'rentify-t05c21.firebasestorage.app',
    iosBundleId: 'com.example.rentify',
  );
}
