# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Lấy mã nguồn
      - uses: actions/checkout@v4

      # Cài đặt Flutter SDK
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3' # Chọn phiên bản Flutter phù hợp
          channel: 'stable'

      # Kiểm tra phiên bản Flutter
      - name: Check Flutter version
        run: flutter --version

      # Cài đặt dependencies
      - name: Install dependencies
        run: flutter pub get
        env:
          PUB_CACHE: /home/runner/.pub-cache

      # Kiểm tra định dạng mã nguồn (tùy chọn)
      # - name: Verify formatting
      #   run: flutter format --set-exit-if-changed .

      # Phân tích mã nguồn
      - name: Analyze project source
        run: flutter analyze

      # Chạy các bài kiểm tra
      - name: Run tests
        run: flutter test