name: Flutter CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Lấy mã nguồn
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      # Bước 2: Cài Flutter
      - name: 🔧 Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'
          channel: 'stable'

      # Bước 3: Kiểm tra phiên bản Flutter
      - name: 🔍 Check Flutter version
        run: flutter --version

      # Bước 4: Cài dependencies
      - name: 📦 Install dependencies
        run: flutter pub get
        env:
          PUB_CACHE: /home/runner/.pub-cache

      # Bước 5: Kiểm tra định dạng mã (tuỳ chọn)
      # - name: 📐 Format check
      #   run: flutter format --set-exit-if-changed .

      # Bước 6: Phân tích mã nguồn - chỉ fail nếu có lỗi thực sự
      - name: 🔎 Analyze Dart code (fail only on errors)
        run: |
          flutter analyze > analyze.log
          cat analyze.log
          if grep -q "error •" analyze.log; then
            echo "❌ Có lỗi nghiêm trọng (error) trong flutter analyze"
            exit 1
          else
            echo "✅ Không có lỗi nghiêm trọng"
          fi

      # Bước 7: Chạy test - không chặn build nếu lỗi
      #- name: ✅ Run tests (không chặn build nếu fail)
      #  run: |
      #    if flutter test; then
      #     echo "✅ Tests passed"
       #   else
      #      echo "⚠️ Tests failed — nhưng không chặn CI"
      #    fi
